//
// Created by berke on 4/29/2026.
//

#ifndef WOLFY_ENGINE_CONFIG_H
#define WOLFY_ENGINE_CONFIG_H

#define MAX_FLOOR_COUNT 3
#define BOUNDARY_COUNT MAX_FLOOR_COUNT + 1

#endif //WOLFY_ENGINE_CONFIG_H